import type { VaccineType, AdministrationRoute } from '../types/vaccination.js';

export const VACCINE_CATEGORY_SLUG = 'vaccination-vaccines';

export interface LaboratorySeed {
  name: string;
}

export interface VaccineProductSeed {
  name: string;
  laboratory: string;
  species: string[];
  vaccineType: VaccineType;
  administrationRoute: AdministrationRoute;
  minimumAgeMonths?: number;
  scheduleDoses?: number;
  scheduleIntervalDays?: number;
  suggestedPrice?: string;
  notes?: string;
}

export const LABORATORIES: LaboratorySeed[] = [
  { name: 'MSD Animal Health' },
  { name: 'Zoetis' },
  { name: 'Boehringer Ingelheim' },
  { name: 'Virbac' },
  { name: 'Biogénesis Bagó' },
  { name: 'Vetanco' },
];

export const VACCINE_PRODUCTS: VaccineProductSeed[] = [
  // === CANINOS — NÚCLEO ===
  {
    name: 'Nobivac Puppy DP',
    laboratory: 'MSD Animal Health',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 1,
    scheduleDoses: 1,
    scheduleIntervalDays: 21,
    suggestedPrice: '8500',
    notes: 'Cachorro temprano. Distemper + Parvo.',
  },
  {
    name: 'Nobivac DHPPi',
    laboratory: 'MSD Animal Health',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 3,
    scheduleIntervalDays: 21,
    suggestedPrice: '12000',
    notes: 'Distemper, Hepatitis, Parvo, Parainfluenza.',
  },
  {
    name: 'Nobivac Lepto',
    laboratory: 'MSD Animal Health',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '9000',
    notes: 'Leptospirosis 4 serogrupos.',
  },
  {
    name: 'Vanguard Plus 5/CV-L',
    laboratory: 'Zoetis',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 3,
    scheduleIntervalDays: 21,
    suggestedPrice: '11000',
    notes: 'Quintuple + Coronavirus + Leptospirosis.',
  },
  {
    name: 'Vanguard Plus 5/L',
    laboratory: 'Zoetis',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 3,
    scheduleIntervalDays: 21,
    suggestedPrice: '10500',
  },
  {
    name: 'Eurican DAP',
    laboratory: 'Boehringer Ingelheim',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 28,
    suggestedPrice: '11500',
    notes: 'Distemper, Adenovirus, Parvo.',
  },
  {
    name: 'Eurican DAPPi-LR',
    laboratory: 'Boehringer Ingelheim',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 3,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '14000',
    notes: 'Séxtuple + rabia. Refuerzo anual.',
  },
  {
    name: 'Canigen Puppy 2b',
    laboratory: 'Virbac',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 1,
    scheduleDoses: 1,
    scheduleIntervalDays: 21,
    suggestedPrice: '8000',
    notes: 'Distemper + Parvo cachorro.',
  },
  {
    name: 'Canigen DHA2PPi/L',
    laboratory: 'Virbac',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 3,
    scheduleIntervalDays: 21,
    suggestedPrice: '11000',
    notes: 'Polivalente canina.',
  },
  {
    name: 'Biocan Novel DHPPi+L4',
    laboratory: 'Biogénesis Bagó',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 3,
    scheduleIntervalDays: 21,
    suggestedPrice: '9500',
  },

  // === CANINOS — RABIA ===
  {
    name: 'Nobivac Rabia',
    laboratory: 'MSD Animal Health',
    species: ['dog', 'cat'],
    vaccineType: 'rabies',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 3,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '7000',
  },
  {
    name: 'Defensor 1',
    laboratory: 'Zoetis',
    species: ['dog', 'cat'],
    vaccineType: 'rabies',
    administrationRoute: 'intramuscular',
    minimumAgeMonths: 3,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '6500',
  },
  {
    name: 'Rabigen Mono',
    laboratory: 'Virbac',
    species: ['dog', 'cat'],
    vaccineType: 'rabies',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 3,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '6800',
  },
  {
    name: 'Rabisin',
    laboratory: 'Boehringer Ingelheim',
    species: ['dog', 'cat'],
    vaccineType: 'rabies',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 3,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '7200',
  },
  {
    name: 'Biocan R',
    laboratory: 'Biogénesis Bagó',
    species: ['dog', 'cat'],
    vaccineType: 'rabies',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 3,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '5500',
  },

  // === CANINOS — NO NÚCLEO ===
  {
    name: 'Nobivac KC',
    laboratory: 'MSD Animal Health',
    species: ['dog'],
    vaccineType: 'non_core',
    administrationRoute: 'intranasal',
    minimumAgeMonths: 2,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '13000',
    notes: 'Tos de las perreras (Bordetella + Parainfluenza).',
  },
  {
    name: 'Bronchi-Shield III',
    laboratory: 'Boehringer Ingelheim',
    species: ['dog'],
    vaccineType: 'non_core',
    administrationRoute: 'intranasal',
    minimumAgeMonths: 2,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '14000',
    notes: 'Bordetella + Adenovirus + Parainfluenza intranasal.',
  },
  {
    name: 'Canigen Puppy KC',
    laboratory: 'Virbac',
    species: ['dog'],
    vaccineType: 'non_core',
    administrationRoute: 'intranasal',
    minimumAgeMonths: 3,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '12500',
    notes: 'Bordetella + Parainfluenza.',
  },
  {
    name: 'Vanguard CIV H3N2/H3N8',
    laboratory: 'Zoetis',
    species: ['dog'],
    vaccineType: 'non_core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '15000',
    notes: 'Influenza canina bivalente.',
  },
  {
    name: 'Nobivac Myxo-RHD Plus',
    laboratory: 'MSD Animal Health',
    species: ['dog'],
    vaccineType: 'non_core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 4,
    scheduleDoses: 2,
    scheduleIntervalDays: 28,
    suggestedPrice: '16000',
    notes: 'Leishmaniosis canina.',
  },
  {
    name: 'Letifend',
    laboratory: 'MSD Animal Health',
    species: ['dog'],
    vaccineType: 'non_core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 6,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '25000',
    notes: 'Leishmaniosis (proteína recombinante).',
  },

  // === FELINOS — NÚCLEO ===
  {
    name: 'Nobivac Tricat Trio',
    laboratory: 'MSD Animal Health',
    species: ['cat'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '13000',
    notes: 'Triple felina: Panleucopenia + Rinotraqueitis + Calicivirus.',
  },
  {
    name: 'Felocell CVR',
    laboratory: 'Zoetis',
    species: ['cat'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '12000',
    notes: 'Triple felina.',
  },
  {
    name: 'Purevax RCPCh',
    laboratory: 'Boehringer Ingelheim',
    species: ['cat'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '14500',
    notes: 'Triple felina + Chlamydia. Sin adyuvante.',
  },
  {
    name: 'Purevax RCP',
    laboratory: 'Boehringer Ingelheim',
    species: ['cat'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '13500',
    notes: 'Triple felina sin adyuvante.',
  },
  {
    name: 'Feligen CRP',
    laboratory: 'Virbac',
    species: ['cat'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '11500',
    notes: 'Triple felina.',
  },

  // === FELINOS — NO NÚCLEO ===
  {
    name: 'Nobivac FeLV',
    laboratory: 'MSD Animal Health',
    species: ['cat'],
    vaccineType: 'non_core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '14000',
    notes: 'Leucemia felina. Testear FeLV antes.',
  },
  {
    name: 'Purevax FeLV',
    laboratory: 'Boehringer Ingelheim',
    species: ['cat'],
    vaccineType: 'non_core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '15000',
    notes: 'Leucemia felina sin adyuvante (canarypox). Testear FeLV antes.',
  },
  {
    name: 'Felocell 4',
    laboratory: 'Zoetis',
    species: ['cat'],
    vaccineType: 'non_core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 2,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '13500',
    notes: 'Triple felina + Chlamydia.',
  },
  {
    name: 'Purevax Rabies',
    laboratory: 'Boehringer Ingelheim',
    species: ['cat'],
    vaccineType: 'rabies',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 3,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '9000',
    notes: 'Rabia felina sin adyuvante (canarypox).',
  },

  // === CANINOS + FELINOS — POLIVALENTES ===
  {
    name: 'Eurican DAPPi-L + Rabisin',
    laboratory: 'Boehringer Ingelheim',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 3,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '16000',
    notes: 'Polivalente + rabia combinada.',
  },
  {
    name: 'Vanguard Plus 5/CV-L/R',
    laboratory: 'Zoetis',
    species: ['dog'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 3,
    scheduleDoses: 1,
    scheduleIntervalDays: 365,
    suggestedPrice: '15000',
    notes: 'Quintuple + Coronavirus + Lepto + Rabia.',
  },

  // === EQUINOS ===
  {
    name: 'Fluvac Innovator EHV-4/1',
    laboratory: 'Zoetis',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'intramuscular',
    minimumAgeMonths: 3,
    scheduleDoses: 3,
    scheduleIntervalDays: 30,
    suggestedPrice: '22000',
    notes: 'Herpesvirus equino 1 y 4.',
  },
  {
    name: 'Proteq Flu',
    laboratory: 'Boehringer Ingelheim',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'intramuscular',
    minimumAgeMonths: 4,
    scheduleDoses: 2,
    scheduleIntervalDays: 42,
    suggestedPrice: '20000',
    notes: 'Influenza equina (canarypox).',
  },
  {
    name: 'Pneumabort K+1B',
    laboratory: 'Zoetis',
    species: ['other'],
    vaccineType: 'non_core',
    administrationRoute: 'intramuscular',
    minimumAgeMonths: 5,
    scheduleDoses: 2,
    scheduleIntervalDays: 30,
    suggestedPrice: '18000',
    notes: 'EHV-1 para prevenir aborto en yeguas.',
  },

  // === BOVINOS ===
  {
    name: 'Biovac J5',
    laboratory: 'Biogénesis Bagó',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 1,
    scheduleDoses: 2,
    scheduleIntervalDays: 30,
    suggestedPrice: '3500',
    notes: 'E. coli J5 – mastitis / endotoxemia.',
  },
  {
    name: 'Bioabortogen H',
    laboratory: 'Biogénesis Bagó',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 3,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '3000',
    notes: 'IBR + BVD + Leptospirosis + Campylobacter.',
  },
  {
    name: 'Bovigen Clostri Plus',
    laboratory: 'Biogénesis Bagó',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 1,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '2500',
    notes: 'Polivalente clostridial 8 cepas.',
  },
  {
    name: 'Rotatec J5',
    laboratory: 'Biogénesis Bagó',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 7,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '4000',
    notes: 'Rotavirus + Coronavirus + E. coli neonatal.',
  },
  {
    name: 'Neumobac',
    laboratory: 'Vetanco',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 1,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '3200',
    notes: 'Neumonía bovina (Mannheimia + Pasteurella).',
  },
  {
    name: 'Vedevax Block',
    laboratory: 'Vetanco',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 6,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '3800',
    notes: 'IBR marcada (gE-). Permite diferenciar vacunados de infectados.',
  },

  // === OVINOS ===
  {
    name: 'Clostrivet Polivalente',
    laboratory: 'Vetanco',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 1,
    scheduleDoses: 2,
    scheduleIntervalDays: 21,
    suggestedPrice: '1800',
    notes: 'Polivalente clostridial ovino/bovino.',
  },

  // === PORCINOS ===
  {
    name: 'Ingelvac CircoFLEX',
    laboratory: 'Boehringer Ingelheim',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'intramuscular',
    minimumAgeMonths: 1,
    scheduleDoses: 1,
    suggestedPrice: '5500',
    notes: 'Circovirus porcino tipo 2 (PCV2).',
  },
  {
    name: 'Ingelvac PRRS MLV',
    laboratory: 'Boehringer Ingelheim',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'intramuscular',
    minimumAgeMonths: 1,
    scheduleDoses: 1,
    suggestedPrice: '4500',
    notes: 'PRRS virus vivo modificado.',
  },
  {
    name: 'Porcilis PCV M Hyo',
    laboratory: 'MSD Animal Health',
    species: ['other'],
    vaccineType: 'core',
    administrationRoute: 'intramuscular',
    minimumAgeMonths: 1,
    scheduleDoses: 1,
    suggestedPrice: '6000',
    notes: 'PCV2 + Mycoplasma hyopneumoniae combinada.',
  },

  // === AVES ===
  {
    name: 'Nobilis Ma5 + Clone 30',
    laboratory: 'MSD Animal Health',
    species: ['bird'],
    vaccineType: 'core',
    administrationRoute: 'oral',
    minimumAgeMonths: 0,
    scheduleDoses: 1,
    suggestedPrice: '800',
    notes: 'Newcastle + Bronquitis infecciosa aviar. Agua de bebida.',
  },
  {
    name: 'Vectormune HVT-IBD',
    laboratory: 'Biogénesis Bagó',
    species: ['bird'],
    vaccineType: 'core',
    administrationRoute: 'subcutaneous',
    minimumAgeMonths: 0,
    scheduleDoses: 1,
    suggestedPrice: '500',
    notes: 'Gumboro (IBD) vectorizada. In-ovo o al día de edad.',
  },
];
